version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    networks:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'tune-vault'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
